import type { TeamMember } from "./types";

export const teamMembers: TeamMember[] = [
  {
    id: "maya-chen",
    name: "Maya Chen",
    role: "Founder & Creative Director",
    focus: "Brand systems & high-converting marketing sites",
    bio: "Maya founded Northline to help growing B2B companies show up online with the same clarity they bring to the work itself. She leads creative direction across branding and web engagements, and stays in the room from first diagnosis through launch.",
    photo: "/images/team/maya-chen.jpg",
    linkedin: "https://www.linkedin.com/in/maya-chen-northline/",
    x: "https://x.com/mayachen",
  },
  {
    id: "jordan-ellis",
    name: "Jordan Ellis",
    role: "Head of Strategy",
    focus: "Positioning, pipeline diagnosis & engagement scope",
    bio: "Jordan works with clients to clarify goals, map what “better customers” means in numbers the business already watches, and keep every engagement aligned to those priorities. If the brief is fuzzy, the work starts with Jordan.",
    photo: "/images/team/jordan-ellis.jpg",
    linkedin: "https://www.linkedin.com/in/jordan-ellis-strategy/",
  },
  {
    id: "sofia-ramirez",
    name: "Sofia Ramirez",
    role: "Design Lead",
    focus: "Visual systems for web, brand & campaign assets",
    bio: "Sofia oversees visual design for websites, brand systems, and marketing materials with a bias toward clarity over decoration. She turns strategy into interfaces and assets teams can actually ship without a style-guide lecture.",
    photo: "/images/team/sofia-ramirez.jpg",
    linkedin: "https://www.linkedin.com/in/sofia-ramirez-design/",
  },
  {
    id: "nathan-brooks",
    name: "Nathan Brooks",
    role: "Development Lead",
    focus: "Front-end systems, performance & accessibility",
    bio: "Nathan guides front-end implementation so every site is fast, accessible, and wired into the tools the client already uses. He owns the gap between approved design and something that holds up after launch.",
    photo: "/images/team/nathan-brooks.jpg",
    linkedin: "https://www.linkedin.com/in/nathan-brooks-dev/",
  },
  {
    id: "priya-nair",
    name: "Priya Nair",
    role: "Marketing Manager",
    focus: "SEO, lifecycle email & demand programs",
    bio: "Priya coordinates SEO, social, and email programs that keep clients visible after the site ships. She connects channel work back to the same qualification story as the website, so traffic is not the only scoreboard.",
    photo: "/images/team/priya-nair.jpg",
    linkedin: "https://www.linkedin.com/in/priya-nair-growth/",
    x: "https://x.com/priyanair",
  },
  {
    id: "liam-okafor",
    name: "Liam Okafor",
    role: "Content Producer",
    focus: "Narrative, photography & short-form video",
    bio: "Liam handles copywriting, photography coordination, and video support so brand stories stay consistent across the site and campaigns. He translates strategy into language and frames that do not sound like tip-blog filler.",
    photo: "/images/team/liam-okafor.jpg",
    linkedin: "https://www.linkedin.com/in/liam-okafor/",
    x: "https://x.com/liamokafor",
  },
];
